version: "3.7"
services:
  pyco:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5500:5500"
    command: "pyco"
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5510:5510"
    command: "admin"